# This is the configuration used to check the rubocop source code.

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
